### ISSUE TITLE
Results are not appearing most of the time

### ISSUE THREAD

**Issue by benide** [shg/ob-julia-vterm.el#13]
I am having a strange problem where the results only rarely appear when I run a Julia code block. The "Evaluating ... " line appears very briefly in the results and then disappears, and then the results are blank. When I go to the julia-vterm buffer, the correct output did occur, it just didn't end up in the org file.

I've tried various combinations of options with session, results, and async. It seems entirely random which options I'm using when the results do work 5-10% of the time, but they more often (still infrequently) work when I've let it sit idle for awhile. I genuinely have no idea why this would be the case, but it's what I've noticed.

I tried stripping down my config. I'm using straight and use-package to manage my packages, but other than that I'm only loading julia-mode, vterm, julia-vterm, ob-julia-vterm, and org with no extraneous options.

What should I do to troubleshoot this?

Thanks for making this package! Even though I haven't gotten it working yet, it looks great!

**Comment by shg** [comment]
Thank you for reporting the issue. It seems that something is wrong in async execution. Let me check. Could you let me know your environment?

For the time being, you can try a previous version 0.2. In that version, async execution has not been implemented yet and the issue should not exist.

**Comment by benide** [comment]
I'm on linux, emacs is compiled from master using `--with-native-compilation --with-pgtk`. Saw the problem with my old build from January and an updated build from yesterday. Julia is compiled from the 1.8 branch, but I tried the executable 1.7.3 downloaded from the website as well.

Going back to 0.2 works perfectly, I think at even at that commit this is going to work well. Async is nice obviously, but I can wait! Thanks, let me know if I can help somehow.

**Comment by erikbackman** [comment]
Same issue here. Something trivial like `println("Hello")` works but not much else.
I'm trying to convert my linear algebra notes from using sagemath to julia and it seems impossible to output matrices.

On Gentoo Linux, Emacs 28 (native comp) and Julia 1.7.3.

**Comment by shg** [comment]
Thank you for the report. I test the package in some environments but I have not been able to reproduce the problem yet.

For Asynchronous execution, the results in the document is updated by detecting that the results have been saved in a temporary file. I suspect the issue may be caused by a failure to retrieve the contents of the results due to some timing problems. Let me check a bit further.

**Comment by shg** [comment]
Sorry it took a while. I observed the reported issue occurs in a Linux environment. Could you guys please try the following version and check the issue still exists?

https://gist.github.com/shg/ad0214069d3204fc5835db0e30ca3079

**Comment by shg** [comment]
I updated master anyway.

**Comment by benide** [comment]
Sorry for the delay, I will test it this weekend and let you know. Thanks!

**Comment by benide** [comment]
I haven't used the most up to date version extensively yet, but results have appeared as they should every single time. Thanks! I'm closing this. If I run into anything else, I'll let you know.
