### ISSUE TITLE
Macro not defined when the module is loaded in the same block

### ISSUE THREAD

**Issue by shg** [shg/ob-julia-vterm.el#2]
```
#+BEGIN_SRC: julia
using Printf
@printf("This results in an error: @printf not defined")
#+END_SRC
```

**Comment by shg** [comment]
```
#+BEGIN_SRC: julia
using Printf
#+END_SRC

#+BEGIN_SRC: julia
@printf("This works because the macro is already defined when it needs to be expanded")
#+END_SRC
```

**Comment by MasonProtter** [comment]
This can be fixed by replacing an `Expr(:block, ...)` with `Expr(:toplevel, ...)`
```julia
julia> eval(Expr(:block, :(using Printf), :(@printf("This results in an error: @printf not defined"))))
ERROR: LoadError: UndefVarError: @printf not defined
Stacktrace:
 [1] top-level scope
   @ :0
 [2] eval
   @ ./boot.jl:373 [inlined]
 [3] eval(x::Expr)
   @ Base.MainInclude ./client.jl:453
 [4] top-level scope
   @ REPL[1]:1
in expression starting at REPL[1]:1

julia> eval(Expr(:toplevel, :(using Printf), :(@printf("This works because the macro is already defined when it needs to be expanded"))))
This works because the macro is already defined when it needs to be expanded
```

**Comment by shg** [comment]
Thank you for the suggestion. But I think that requires the source code be splited into two expressions to work, which is not generally simple. Without splitting, it results in the same error.

```julia
julia> eval(Expr(:toplevel, quote
           using Printf
           @printf("This results in an error: @printf not defined")
       end))
ERROR: LoadError: UndefVarError: @printf not defined
```

**Comment by MasonProtter** [comment]
Sure, if the user explicitly writes a `begin` statement in their code, then it won’t work, but that’s their fault. 

There’s no splitting that needs to be done here, you just take in the top level expression, parse it, then do `ex.head = :toplevel`

**Comment by MasonProtter** [comment]
I implemented this for julia-snail recently, but I find your code a bit harder to navigate and understand what you’re doing so I haven’t made a PR here yet. Here’s what I did in Julia-snail if you want to use that:  https://github.com/gcv/julia-snail/pull/78

Otherwise, I can try to figure it out later and open a PR.

**Comment by shg** [comment]
I am currently working on a relatively significant update involving asynchronous execution. So please be informed that the code of the related part may change.

**Comment by shg** [comment]
Fixed in the current version.
