### ISSUE TITLE
The src code block does not actually executed.

### ISSUE THREAD

**Issue by timze216** [shg/ob-julia-vterm.el#24]
Hi, Thanks for your great work!   

I try to run async  Julia src block with ob-julia-vterm on emacs 30, but it alway fails to send my code into Julia-vterm, and every time I try, it just returns an immediate completion prompt, but it is actually  not performed.

here is the detailed record:
1. install ob-julia-vterm, vterm and julia-mode,
2. config the org-babel as in readme.md
3. open a new org file:
```org
#+begin_src julia
a = 1
#+end_src
```
 press C-c C-c, then the output is: 
```
#+RESULTS:
: Executing... 287318cc
```
And there is an immediate prompt in the message buffer:
```
Executing Julia code block at position 729...
Code block evaluation complete.
```
I can see there is a session called *Julia:main*, but nothing have put into it. 

Do you have any suggestion for this?  Thanks!

**Comment by shg** [comment]
Hi @timze216 Thank you for the report. Is julia-vterm.el working? You can check it by:
1.  create and open a Julia script file (e.g. test.jl) and turn on julia-vterm-mode
2. write arbitrary julia code such as `a = 1`
3. send buffer to REPL with `C-c C-b`

**Comment by timze216** [comment]
Yes, I can confirm that the julia-vterm works well with the Julia script. 

But in org-mode src code block, it seems the code do not pass to the Julia-vterm,
I use doom, with these configures:
```lisp 
(org-babel-do-load-languages
 'org-babel-load-languages
 '(
   (julia . t)
   (julia-vterm . t)
   ))
```
 then here are the results with  header arg "julia" and "Julia-vterm"
```
#+begin_src julia
using Dates
@show now()

#+RESULTS:
: 2023-09-30T21:44:18.704
```

```
#+begin_src julia-vterm
using Dates
@show now()
#+end_src

#+RESULTS:
: Executing... e88717d3
```

Still have no idea for what causes this.

**Comment by shg** [comment]
Do you mean that it works with `julia` as language but not with `julia-vterm`?

**Comment by timze216** [comment]
No, the “julia” src code here will use the default Julia in emacs ESS, it works well but doesn’t support asynchronous, and the “julia-vterm” should pass the code to julia-vterm, but it seems doesn’t works.  I have trouble in finding out what is going wrong😀

Thanks for your time.

**Comment by shg** [comment]
Thank you for clarifying. I am on Emacs 29 and haven't tried Emacs 30 yet. I am also not using Doom, so it is difficult to narrow down the cause of the problem for now. I will try to reproduce the problem when I have time, so please provide me with the versions of the OS, Emacs, Org, julia-vterm, ob-julia-vterm.

Also, it would be helpful if you can test in a minimal environment. You can run Emacs with the HOME environment variable set to a temporary directory and install only the necessary packages.

By the way, I assume you are trying to use ob-julia-vterm for the first time. Or have you used it before in any previous environments (such as Emacs 29)?

**Comment by timze216** [comment]
Still doesn't work in Emacs 29, seems like it's very related to my configuration. I will find time to test it in a new environment. Thanks again for yourassistance again. Have a nice day!

**Comment by shg** [comment]
@timze216 Sorry I couldn't help you figure out the issue. Please ask again if you find any possible package issues.
